// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseFile(arg1, arg2) {
  return window['go']['app']['App']['CloseFile'](arg1, arg2);
}

export function DomReady(arg1) {
  return window['go']['app']['App']['DomReady'](arg1);
}

export function GetActiveFile(arg1) {
  return window['go']['app']['App']['GetActiveFile'](arg1);
}

export function GetFileData(arg1, arg2) {
  return window['go']['app']['App']['GetFileData'](arg1, arg2);
}

export function GetOpenFiles(arg1) {
  return window['go']['app']['App']['GetOpenFiles'](arg1);
}

export function ParseFile(arg1, arg2) {
  return window['go']['app']['App']['ParseFile'](arg1, arg2);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function SetActiveFile(arg1, arg2) {
  return window['go']['app']['App']['SetActiveFile'](arg1, arg2);
}

export function ValidateLogFormat(arg1, arg2) {
  return window['go']['app']['App']['ValidateLogFormat'](arg1, arg2);
}

export function SelectSaveLocation(arg1) {
  return window['go']['app']['App']['SelectSaveLocation'](arg1);
}

export function ExportToExcel(arg1) {
  return window['go']['app']['App']['ExportToExcel'](arg1);
}
