// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {models} from '../models';
import {app} from '../models';

export function CloseFile(arg1:context.Context,arg2:string):Promise<boolean>;

export function DomReady(arg1:context.Context):Promise<void>;

export function GetActiveFile(arg1:context.Context):Promise<string>;

export function GetFileData(arg1:context.Context,arg2:string):Promise<models.LogFile>;

export function GetOpenFiles(arg1:context.Context):Promise<Array<string>>;

export function ParseFile(arg1:context.Context,arg2:app.ParseFileRequest):Promise<app.ParseFileResponse>;

export function SelectFile(arg1:context.Context):Promise<app.SelectFileResponse>;

export function SetActiveFile(arg1:context.Context,arg2:string):Promise<boolean>;

export function ValidateLogFormat(arg1:context.Context,arg2:app.ValidateFormatRequest):Promise<app.ValidateFormatResponse>;
