// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {app} from '../models';

export function CloseFile(arg1:string):Promise<boolean>;

export function GetActiveFile():Promise<string>;

export function GetFileData(arg1:string):Promise<models.LogFile>;

export function GetOpenFiles():Promise<Array<string>>;

export function ParseFile(arg1:app.ParseFileRequest):Promise<app.ParseFileResponse>;

export function SelectFile():Promise<app.SelectFileResponse>;

export function SetActiveFile(arg1:string):Promise<boolean>;

export function ValidateLogFormat(arg1:app.ValidateFormatRequest):Promise<app.ValidateFormatResponse>;
