// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseFile(arg1) {
  return window['go']['app']['App']['CloseFile'](arg1);
}

export function GetActiveFile() {
  return window['go']['app']['App']['GetActiveFile']();
}

export function GetFileData(arg1) {
  return window['go']['app']['App']['GetFileData'](arg1);
}

export function GetOpenFiles() {
  return window['go']['app']['App']['GetOpenFiles']();
}

export function ParseFile(arg1) {
  return window['go']['app']['App']['ParseFile'](arg1);
}

export function SelectFile() {
  return window['go']['app']['App']['SelectFile']();
}

export function SetActiveFile(arg1) {
  return window['go']['app']['App']['SetActiveFile'](arg1);
}

export function ValidateLogFormat(arg1) {
  return window['go']['app']['App']['ValidateLogFormat'](arg1);
}
